<?php
/**
 * Plugin Name: Free Posts in Elementor
 * Description: Works like Loop Grid and Posts of Elementor and it is completely free and safe.
 * Version: 1.1
 * Requires at least: 5.8
 * Requires PHP: 7.4
 * Author: Md Emon Sharkar
 * Author URI: mailto:emonsharkar.2000@gmail.com
 * Text Domain: free-posts-in-elementor
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

define( 'FPE_VERSION', '1.1' );
define( 'FPE_PLUGIN_FILE', __FILE__ );
define( 'FPE_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'FPE_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

final class FPE_Free_Posts_In_Elementor {

    const OPTION_ENABLE_SINGLE_TEMPLATE = 'fpe_enable_single_template';

    private static $instance = null;

    public static function instance() {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action( 'plugins_loaded', [ $this, 'bootstrap' ] );
    }

    public function bootstrap() {
        // Elementor must be loaded.
        if ( ! did_action( 'elementor/loaded' ) ) {
            add_action( 'admin_notices', [ $this, 'admin_notice_missing_elementor' ] );
            return;
        }

        // Register widget + assets.
        add_action( 'elementor/widgets/register', [ $this, 'register_widgets' ] );
        // Back-compat for older Elementor versions.
        add_action( 'elementor/widgets/widgets_registered', [ $this, 'register_widgets_legacy' ] );

        add_action( 'elementor/frontend/after_enqueue_styles', [ $this, 'enqueue_frontend_styles' ] );

        // Optional Single Post template (plugin-generated).
        add_action( 'admin_menu', [ $this, 'register_settings_page' ] );
        add_action( 'admin_init', [ $this, 'register_settings' ] );
        add_filter( 'template_include', [ $this, 'maybe_use_single_template' ], 99 );
        add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_single_template_assets' ] );
    }

    public function admin_notice_missing_elementor() {
        if ( ! current_user_can( 'activate_plugins' ) ) {
            return;
        }
        $message = esc_html__( 'Free Posts in Elementor requires Elementor to be installed and activated.', 'free-posts-in-elementor' );
        echo '<div class="notice notice-warning"><p>' . $message . '</p></div>';
    }

    public function enqueue_frontend_styles() {
        wp_register_style(
            'fpe-widget',
            FPE_PLUGIN_URL . 'assets/css/widget.css',
            [],
            FPE_VERSION
        );
        wp_enqueue_style( 'fpe-widget' );
    }

    public function register_settings_page() {
        add_options_page(
            __( 'Free Posts Template', 'free-posts-in-elementor' ),
            __( 'Free Posts Template', 'free-posts-in-elementor' ),
            'manage_options',
            'free-posts-in-elementor',
            [ $this, 'render_settings_page' ]
        );
    }

    public function register_settings() {
        register_setting(
            'fpe_settings',
            self::OPTION_ENABLE_SINGLE_TEMPLATE,
            [
                'type' => 'boolean',
                'sanitize_callback' => function ( $value ) {
                    return (bool) $value;
                },
                'default' => false,
            ]
        );
    }

    public function render_settings_page() {
        if ( ! current_user_can( 'manage_options' ) ) {
            return;
        }
        $enabled = (bool) get_option( self::OPTION_ENABLE_SINGLE_TEMPLATE, false );
        ?>
        <div class="wrap">
            <h1><?php echo esc_html__( 'Free Posts in Elementor - Single Post Template', 'free-posts-in-elementor' ); ?></h1>
            <p><?php echo esc_html__( 'Enable a lightweight single post layout generated by this plugin (similar to your provided design).', 'free-posts-in-elementor' ); ?></p>
            <form method="post" action="options.php">
                <?php settings_fields( 'fpe_settings' ); ?>

                <table class="form-table" role="presentation">
                    <tbody>
                    <tr>
                        <th scope="row"><?php echo esc_html__( 'Enable Single Post Template', 'free-posts-in-elementor' ); ?></th>
                        <td>
                            <label>
                                <input type="checkbox" name="<?php echo esc_attr( self::OPTION_ENABLE_SINGLE_TEMPLATE ); ?>" value="1" <?php checked( $enabled ); ?> />
                                <?php echo esc_html__( 'Use plugin template for single blog posts', 'free-posts-in-elementor' ); ?>
                            </label>
                            <p class="description"><?php echo esc_html__( 'If enabled, the plugin will render a fast, safe, styled single post page without Elementor Pro.', 'free-posts-in-elementor' ); ?></p>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <?php submit_button(); ?>
            </form>
        </div>
        <?php
    }

    public function maybe_use_single_template( $template ) {
        $enabled = (bool) get_option( self::OPTION_ENABLE_SINGLE_TEMPLATE, false );
        if ( ! $enabled ) {
            return $template;
        }

        // Only override single posts (not pages, not archives).
        if ( is_singular( 'post' ) ) {
            $custom = FPE_PLUGIN_DIR . 'templates/single-free-posts.php';
            if ( file_exists( $custom ) ) {
                return $custom;
            }
        }
        return $template;
    }

    public function enqueue_single_template_assets() {
        $enabled = (bool) get_option( self::OPTION_ENABLE_SINGLE_TEMPLATE, false );
        if ( ! $enabled ) {
            return;
        }
        if ( is_singular( 'post' ) ) {
            wp_register_style(
                'fpe-single',
                FPE_PLUGIN_URL . 'assets/css/single.css',
                [],
                FPE_VERSION
            );
            wp_enqueue_style( 'fpe-single' );
        }
    }

    public function register_widgets( $widgets_manager ) {
        require_once FPE_PLUGIN_DIR . 'includes/class-free-posts-widget.php';
        $widgets_manager->register( new \FPE_Free_Posts_Widget() );
    }

    public function register_widgets_legacy() {
        // Elementor < 3.5 uses widgets_registered hook.
        if ( did_action( 'elementor/widgets/register' ) ) {
            return;
        }
        if ( ! class_exists( '\\Elementor\\Plugin' ) ) {
            return;
        }
        require_once FPE_PLUGIN_DIR . 'includes/class-free-posts-widget.php';
        \Elementor\Plugin::instance()->widgets_manager->register_widget_type( new \FPE_Free_Posts_Widget() );
    }
}

FPE_Free_Posts_In_Elementor::instance();
